final Map<String, List<String>> cityDistricts = {
  'Dammam': [
    'Al Shatea East',
    'Al Shatea West',
    'Al Murikabat',
    'Al Rayyan',
    'Taibah',
    'Al Rawdah',
    'Al Fardous',
    'Al Manar',
    'Al Nour',
    'Al Mazruiyyah',
    'Al Khalij',
    'Al Faisaliyah',
    'Al Zahour',
    'Al Anud',
    'Al Jalawiyah',
    'Al Nuzha',
    'Al Khaldiyah',
    'Al Fakhiriyah',
    'Al Ittisalat',
    'Al Amal',
    'Al Rihab',
    'Ad Dawasir',
    'Al Adamah',
    'Al Badie',
    'Al Salam',
    'Al Amamrah',
    'Al Qadsiah',
    'Al Nasriah',
    'Al Waha',
    'Al Basatin',
    'Al Jamiein',
  ],
  'Al-Khobar': [
    'Al Khobar North',
    'Al Khobar South',
    'Al Olaya',
    'Al Hizam Al Dhahabi',
    'Al Hizam Al Akhdar',
    'Al Khuzama',
    'Al Rawabi',
    'Al Huda',
    'Al Jesr',
    'Al Rakah South',
    'Al Rakah North',
    'Corniche',
    'Al Jawhara',
    'Al Andalus',
    'Al Bandariyah',
    'Al Aziziyah',
    'Al Souari',
    'Al Buhairah',
    'Al Nawras',
    'Al Lulu',
    'Al Oqail',
    'Al Tahliyah',
    'Al Yarmouk',
    'Al Bahr',
    'Qurtuba',
    'Al Sadfah',
    'Sports City',
    'Al Sobaikha',
  ],
  'Al-Jubail': [
    'Al Yarmouk',
    'Al Fayhaa',
    'Al Firdous',
    'Al Andalus',
    'Al Shati',
    'Al Lulu',
    'Dareen',
    'Jalmudah',
    'Al Waha',
    'Al Riyadh',
    'Al Hijaz',
    'Al Khalij',
    'Al Dana',
    'Al Hamra',
    'Al Rawdah',
    'Taiba',
    'Ghranata',
    'Al Bustan',
    'Qurtuba',
    'Ishbiliyah',
    'Al Khaldiyah',
  ],
  'Al-Qatif': [
    'Al Qatif',
    'Al Qalaa',
    'Al Shatee',
    'Al Dababiyah',
    'Al Bahar',
    'Al Shwaikah',
    'Al Zarah',
    'Al Nasirah',
    'Al Majidiyah',
    'Al Hussain',
    'Al Mishari',
    'Al Mahdood',
    'Al Kuwait',
    'Al Jameeyah',
    'Al Muhandiseen',
    'Al Khaleej',
    'Al Salam',
    'Al Firdous',
    'North Al Nimr',
    'South Al Nimr',
    'Mayas',
    'Al Badiah',
    'Al Reda',
    'Al Zamurdah',
    'Al Shahba',
    'Al Rehab',
    'Al Azdihar',
    'Al Khamisah',
    'King Faisal District',
    'Saihat',
    'Anak',
    'Al Qudaih',
    'Al Awamiyah',
    'Tarout',
    'Sanabis',
    'Al Rubaiyah',
    'Darin',
    'Al Bahari',
    'Al Tobi',
    'Al Jish',
    'Al Malahah',
    'Al Jarariyah',
    'Umm Al Hammam',
    'Umm Al Sahik',
    'Al Ojam',
    'Abu Maan',
  ],
  'Hafar Al-Batin': [
    'Al Baladiyah',
    'Al Khalidiyah',
    'Al Muhammadiyah',
    'Al Yarmuk',
    'Al Fayhaa',
    'Al Rawdah',
    'Qurtubah',
    'Al Nahdah',
    'Al Shifa',
    'Al Sulaimaniyah',
    'Al Safa',
    'Al Rayan',
    'Al Raed',
    'Al Tilal',
    'Ghirnatah',
    'Al Wadi',
    'Al Nakheel',
    'Al Rabee',
    'Fulaij',
    'Abu Musa Al Ashari',
    'Industrial District',
    'Al Batin',
    'Al Moutaa',
    'Qaisumah',
    'Al Qalt',
    'Al Mutayahah South',
  ],
  'Al-Khafji': [
    'King Fahd',
    'Al Aziziyah',
    'Arab Gulf',
    'Al Murooj',
    'Al Faisaliyah',
    'Al Jawhara',
    'Al Salam',
    'Ghornatah',
    'King Faisal',
    'Al Yasmin',
    'Al Khalidiyah',
    'Al Zohour',
    'Abraq Al Khabarit',
    'Ras Mishab',
    'As Saffaniyah',
    'Tanajib',
  ],
  'Abqaiq': [
    'Al Basateen',
    'Al Rawdah',
    'Al Sanaiyah',
    'Al Firdaws',
    'Aramco District',
    'Ishbiliyah',
    'Al Andalus',
    'Al Madinah',
    'Gharnatah',
    'Qurtubah',
    'Al Rabwah',
    'Al Matar',
    'King Faisal',
    'Al Khaleej',
    'Al Nuzhah',
    'Al Majd',
  ],
  'Ras Tanura': [
    'Al Naeem',
    'Al Rawdah',
    'Radwa',
    'Najmah',
    'Qurtubah',
    'Al Danah',
    'Al Muntazah',
    'Al Zuhour',
    'Rahima',
    'King Faisal',
  ],
  'Al-Ahsa': [
    'Al Hofuf',
    'Al Mubarraz',
    'Al Salmaniyah',
    'Al Khalidiyah',
    'Al Mazruiyah',
    'Al Rawdah',
    'Al Naseem',
    'Al Rifaah',
    'Al Jafr',
    'Al Omran',
    'Al Oyoun',
    'Al Taraf',
    'Al Qarah',
    'Al Koot',
    'Al Mahasen',
    'Al Naathil',
    'Al Aramco',
    'Al Rabwah',
    'Al Shubaikah',
    'Al Bustan',
    'Al Jameen',
    'Al Faisaliyah',
    'Al Wusta',
    'Al Khars',
    'Al Hara',
  ],
};

