// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV429Gp53SXdx9IZo71zjhZlHyIKuXg-E',
    appId: '1:712538360785:web:021a480c1452407a8b6ef0',
    messagingSenderId: '712538360785',
    projectId: 'releaf-ec515',
    authDomain: 'releaf-ec515.firebaseapp.com',
    storageBucket: 'releaf-ec515.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCLWsvNMbGKBSOuc7jSNxeBmx2gSDNxA',
    appId: '1:712538360785:android:f4d58185ebfeee518b6ef0',
    messagingSenderId: '712538360785',
    projectId: 'releaf-ec515',
    storageBucket: 'releaf-ec515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmJ9JOnH2nzkupyDPspIfnjADjgwQAPMI',
    appId: '1:712538360785:ios:12485c10d86c72f28b6ef0',
    messagingSenderId: '712538360785',
    projectId: 'releaf-ec515',
    storageBucket: 'releaf-ec515.firebasestorage.app',
    iosBundleId: 'com.example.releafApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmJ9JOnH2nzkupyDPspIfnjADjgwQAPMI',
    appId: '1:712538360785:ios:12485c10d86c72f28b6ef0',
    messagingSenderId: '712538360785',
    projectId: 'releaf-ec515',
    storageBucket: 'releaf-ec515.firebasestorage.app',
    iosBundleId: 'com.example.releafApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV429Gp53SXdx9IZo71zjhZlHyIKuXg-E',
    appId: '1:712538360785:web:926792c482443cb68b6ef0',
    messagingSenderId: '712538360785',
    projectId: 'releaf-ec515',
    authDomain: 'releaf-ec515.firebaseapp.com',
    storageBucket: 'releaf-ec515.firebasestorage.app',
  );
}
